services:
  test:
    build:
      context: .
      target: builder-test
    environment:
      DATABASE_URL: postgresql+psycopg://kubsu:kubsu@db:5432/kubsu
    container_name: tests
    ports:
      - "8001:8001"
    depends_on:
      - db
    command: make test

  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: kubsu
      POSTGRES_PASSWORD: kubsu
      POSTGRES_DB: kubsu
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  app:
    build: .
    image: velvit24/app:latest
    container_name: app
    ports:
      - "58529:8001"
      
volumes:
  pgdata:
