name: Docker Image CI

on:
  push:
    branches:
    - '*'

jobs:
  deploy:
      runs-on: ubuntu-latest
  
      steps:
        - uses: actions/checkout@v3
  
        - name: Copy project to server via SCP
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          run: |
            echo "$SSH_PRIVATE_KEY" > key.pem
            chmod 600 key.pem
            scp -i key.pem -r . maxwell@kubsu.tyvik.ru:/home/maxwell/app
  
        - name: Run app on server via SSH
          run: |
            ssh -i key.pem maxwell@kubsu.tyvik.ru << 'EOF'
              cd /home/maxwell/app
              docker build -t myapp .
              docker stop myapp || true && docker rm myapp || true
              docker run -d -p 58529:58529 --network host --name myapp myapp
            EOF



