name: Docker Image CI

on:
  push:
    branches:
    - '*'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        
        - name: Build project
          run: |
            docker build -t velvit24/my-python-app .
            docker stop velvit24/my-python-app || true && docker rm velvit24/my-python-app || true
            
        - name: Push project
          run: |
            docker push velvit24/my-python-app
  deploy:
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v4

        - name: Install SSH key
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          run: |
            echo "$SSH_PRIVATE_KEY" > key.pem
            chmod 600 key.pem
        - name: Connect ssh
          run: |
            ssh -i key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -p 58529 << 'EOF'
              podman run -d --rm -p 60080:8000 velvit24/my-python-app
            EOF



