name: Docker Image CI

on:
  push:
    branches: 
    - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        make install-dev

    - name: Run tests
      run: make test

  deploy:
      needs: build-and-test
      runs-on: ubuntu-latest
      if: success()
  
      steps:
        - uses: actions/checkout@v3
  
        - name: Copy project to server via SCP
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          run: |
            echo "$SSH_PRIVATE_KEY" > key.pem
            chmod 600 key.pem
            scp -i key.pem -r . maxwell@kubsu.tyvik.ru:/home/youruser/app
  
        - name: Run app on server via SSH
          run: |
            ssh -i key.pem maxwell@kubsu.tyvik.ru << 'EOF'
              cd /home/youruser/app
              docker build -t myapp .
              docker stop myapp || true && docker rm myapp || true
              docker run -d -p 58529:8000 --network host --name myapp myapp
            EOF



