name: Docker Image CI

on:
  push:
    branches:
    - '*'

jobs:
  test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        
        - name: Build tests
          run: |
            docker compose build test db
            docker stop linux-test || true && docker rm linux-test || true
            
        - name: Run tests
          run: |
            docker compose up test
  build:
      needs: test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        
        - name: Build project
          run: |
            docker compose build app
            docker stop linux-app || true && docker rm linux-app || true
        - name: Login in DockerHub
          uses: docker/login-action@v3
          with:
            username: velvit24
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: velvit24/app:latest
  
  deploy:
      needs: build
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v4

        - name: Install SSH key
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          run: |
            echo "$SSH_PRIVATE_KEY" > key.pem
            chmod 600 key.pem
        - name: Connect ssh
          run: |
            ssh -i key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -p 58529 << 'EOF'
              podman pull velvit24/app:latest
              podman stop app || true && podman rm app || true
              podman run -d --network=host --name app velvit24/app:latest
            EOF



