name: Docker Image CI

on:
  push:
    branches:
    - '*'

jobs:
  build:
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v3
        
        - name: Build project
          run: |
            docker build -t velvit24/my-python-app .
            docker stop myapp || true && docker rm myapp || true
        - name: Push project
          run: |
            docker push velvit24/my-python-app
  deploy:
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v4

        - name: Install SSH key
          uses: webfactory/ssh-agent@v0.7.0
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            
        - name: Connect ssh
          run: |
            ssh -o StrictHostKeyChecking=no \
              ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} -p 58529 << 'EOF'
              cd /home/maxwell/app
              docker run -d --rm -p 60080:8000 velvit24/my-python-app
            EOF



